# This workflow will build a package using Gradle and then publish it to GitHub packages when a 'v*' tag is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Publish
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: Decode
        run: |
          echo "${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}" > ~/.gradle/secring.gpg.b64
          base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg

      - name: Publish
        run: >
          ./gradlew publish
          -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }}
          -Psigning.password=${{ secrets.SIGNING_PASSWORD }}
          -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg)
        env:
          ossrh.username: ${{ secrets.OSSRH_USERNAME }}
          ossrh.password: ${{ secrets.OSSRH_PASSWORD }}
