# This workflow will build a package using Gradle and then publish it to GitHub packages when a 'v*' tag is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Publish
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      ossrh.username: ${{ secrets.OSSRH_USERNAME }}
      ossrh.password: ${{ secrets.OSSRH_PASSWORD }}
      signing.secretKey: ${{ secrets.SIGNING_SECRETKEY }}
      signing.password: ${{ secrets.SIGNING_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: Publish
        run: ./gradlew publish
